env: prod
host: https://anissia.net

spring.datasource:
  url: jdbc:mariadb://localhost:3306/anissia
  username: anissia
  password: anissia

elasticsearch:
  url: http://localhost:9200
  username: elastic
  password: elastic

