env: dev
host: http://localhost:5173

spring.r2dbc:
  url: r2dbc:mariadb://localhost:3306/anissia
  username: anissia
  password: anissia
  properties.allowPipelining: true

elasticsearch:
  url: http://localhost:9200
  username:
  password:
